com.instana.plugin.opentelemetry:
  enabled: true

com.instana.ignore:
  arguments:
    - '-javaagent:/opt/otel/opentelemetry-javaagent-all.jar'

com.instana.tracing:
  extra-http-headers:
    - traceparent
    - tracestate
